### ISSUE TITLE
Customize Email template

### ISSUE THREAD

**Issue by ZeroPie** [passlock-dev/ts-clients#19]
hi,
how can i customize the verification emails?

**Comment by thobson** [comment]
Hi. Within the Passlock console settings you can change to logo and sender name, however you can't currently change the content of the email itself. Please see attachment.

<img width="1280" alt="Screenshot 2024-08-18 at 19 28 45" src="https://github.com/user-attachments/assets/96c7be8c-6fbb-4ff1-952a-0b30447019ff">

**Comment by ZeroPie** [comment]
Thanks @thobson 
Is this feature something planned?
Regards

**Comment by thobson** [comment]
It’s a difficult one. The issue is that a developer could sign up for a free Passlock account with no verification then send emails with any content to any recipient via the Passlock mail servers. It would be asking for trouble. 

Some options I’ve considered are:

1. Require email template approval (massive overhead)
2. Allow devs to send the verification mails via their own mail servers (or something like AWS SES, Postmark etc)
3. Keep things as they are but allow developers to use handle verification via some other means then mark users as verified via a REST API. 

The last option is currently my preferred one because I’m adding a REST api for user management anyway. But I’m open to suggestions 🙂
